[tool.poetry]
name = "vocode"
version = "0.1.104"
description = "The all-in-one voice SDK"
authors = ["Ajay Raj <ajay@vocode.dev>"]
license = "MIT License"
readme = "README.md"
homepage = "https://github.com/vocodedev/vocode-python"

[tool.poetry.dependencies]
python = ">=3.8.1,<3.11"
pydantic = "1.10.7"
python-dotenv = ">=0.21.1"
typing-extensions = "4.5.0"
websockets = "10.4"
anyio = "3.6.2"
certifi = "2022.12.7"
cffi = "1.15.1"
charset-normalizer = "3.0.1"
click = "8.1.3"
decorator = "5.1.1"
fastapi = "0.92.0"
h11 = "0.14.0"
idna = "3.4"
numpy = ">=1.21.6"
ply = "3.11"
pycparser = "2.21"
requests = "2.28.2"
six = "1.16.0"
sniffio = "1.3.0"
sounddevice = { version = "0.4.6", optional = true }
starlette = "0.25.0"
urllib3 = "1.26.14"
uvicorn = "0.20.0"
mccabe = "0.7.0"
mypy-extensions = "1.0.0"
packaging = "23.0"
pathspec = "0.11.0"
platformdirs = ">=2.5.2"
pyaudio = { version = "0.2.13", optional = true }
pycodestyle = "2.10.0"
pyflakes = "3.0.1"
pyjwt = "2.6.0"
python-multipart = "0.0.6"
pytz = "2022.7.1"
tomli = "2.0.1"
aiohttp = "3.8.4"
aiosignal = "1.3.1"
async-timeout = "4.0.2"
attrs = "22.2.0"
azure-cognitiveservices-speech = "1.25.0"
dataclasses-json = "0.5.7"
frozenlist = "1.3.3"
langchain = "^0.0.146"
marshmallow = "3.19.0"
marshmallow-enum = "1.5.1"
multidict = "6.0.4"
openai = "0.27.2"
pydub = "0.25.1"
pyyaml = "6.0"
sqlalchemy = "1.4.47"
tenacity = "8.2.2"
tqdm = "4.65.0"
typing-inspect = "0.8.0"
yarl = "1.8.2"
cachetools = "5.3.0"
google-api-core = "2.11.0"
google-auth = "2.16.3"
google-cloud-speech = "2.17.3"
google-cloud-texttospeech = "2.14.1"
googleapis-common-protos = "1.59.0"
grpcio = ">=1.47.0"
grpcio-status = ">=1.47.0"
jinja2 = "3.1.2"
joblib = "1.2.0"
markupsafe = "2.1.2"
nltk = "3.8.1"
proto-plus = "1.22.2"
protobuf = ">=3.19.6"
pyasn1 = "0.4.8"
pyasn1-modules = "0.2.8"
redis = "4.5.3"
regex = "2023.3.23"
rsa = "4.9"
twilio = "7.17.0"
gtts = "2.3.1"
black = "23.1.0"
numexpr = "2.8.4"
openapi-schema-pydantic = "1.2.4"
rev-ai = "2.17.1"
websocket-client = "0.59.0"
elevenlabs = ">=0.2.5"
pyllamacpp = { version = ">=1.0.7", optional = true }
anyascii = { version = "0.3.2", optional = true }
appdirs = { version = "1.4.4", optional = true }
audioread = { version = "3.0.0", optional = true }
babel = { version = "2.12.1", optional = true }
bangla = { version = "0.0.2", optional = true }
bnnumerizer = { version = "0.0.2", optional = true }
bnunicodenormalizer = { version = "0.1.1", optional = true }
build = { version = "0.10.0", optional = true }
cachecontrol = { version = "0.12.11", optional = true }
cleo = { version = "2.0.1", optional = true }
contourpy = { version = "1.0.7", optional = true }
coqpit = { version = "0.0.17", optional = true }
crashtest = { version = "0.4.1", optional = true }
cycler = { version = "0.11.0", optional = true }
cython = { version = "0.29.28", optional = true }
dateparser = { version = "1.1.8", optional = true }
distlib = { version = "0.3.6", optional = true }
docopt = { version = "0.6.2", optional = true }
dulwich = { version = "0.21.3", optional = true }
filelock = { version = "3.12.0", optional = true }
flask = { version = "2.2.3", optional = true }
fonttools = { version = "4.39.3", optional = true }
fsspec = { version = "2023.4.0", optional = true }
g2pkk = { version = "0.1.2", optional = true }
gruut = { version = "2.2.3", optional = true }
gruut-ipa = { version = "0.13.0", optional = true }
gruut-lang-de = { version = "2.0.0", optional = true }
gruut-lang-en = { version = "2.0.0", optional = true }
html5lib = { version = "1.1", optional = true }
importlib-metadata = { version = "6.6.0", optional = true }
importlib-resources = { version = "5.12.0", optional = true }
inflect = { version = "5.6.0", optional = true }
installer = { version = "0.7.0", optional = true }
itsdangerous = { version = "2.1.2", optional = true }
jamo = { version = "0.4.1", optional = true }
jaraco-classes = { version = "3.2.3", optional = true }
jieba = { version = "0.42.1", optional = true }
jsonlines = { version = "1.2.0", optional = true }
jsonschema = { version = "4.17.3", optional = true }
keyring = { version = "23.13.1", optional = true }
kiwisolver = { version = "1.4.4", optional = true }
lazy-loader = { version = "0.2", optional = true }
librosa = { version = "0.10.0.post2", optional = true }
llvmlite = { version = ">=0.38.0rc1", optional = true }
lockfile = { version = "0.12.2", optional = true }
matplotlib = { version = "3.7.1", optional = true }
mecab-python3 = { version = "1.0.5", optional = true }
more-itertools = { version = "9.1.0", optional = true }
mpmath = { version = "1.3.0", optional = true }
msgpack = { version = "1.0.5", optional = true }
networkx = { version = "2.8.8", optional = true }
num2words = { version = "0.5.12", optional = true }
numba = { version = ">=0.55.1", optional = true }
pandas = { version = "2.0.1", optional = true }
pexpect = { version = "4.8.0", optional = true }
pillow = { version = "9.5.0", optional = true }
pkginfo = { version = "1.9.6", optional = true }
pooch = { version = "1.6.0", optional = true }
psutil = { version = "5.9.5", optional = true }
ptyprocess = { version = "0.7.0", optional = true }
pynndescent = { version = "0.5.10", optional = true }
pyparsing = { version = "3.0.9", optional = true }
pypinyin = { version = "0.48.0", optional = true }
pyproject-hooks = { version = "1.0.0", optional = true }
pyrsistent = { version = "0.19.3", optional = true }
pysbd = { version = "0.3.4", optional = true }
python-crfsuite = { version = "0.9.9", optional = true }
python-dateutil = { version = "2.8.2", optional = true }
pytz-deprecation-shim = { version = "0.1.0.post0", optional = true }
rapidfuzz = { version = "2.15.1", optional = true }
requests-toolbelt = { version = "0.10.1", optional = true }
scikit-learn = { version = "1.2.2", optional = true }
scipy = { version = "1.10.1", optional = true }
shellingham = { version = "1.5.0.post1", optional = true }
soundfile = { version = "0.12.1", optional = true }
soxr = { version = "0.3.5", optional = true }
sympy = { version = "1.11.1", optional = true }
tensorboardx = { version = "2.6", optional = true }
threadpoolctl = { version = "3.1.0", optional = true }
tomlkit = { version = "0.11.7", optional = true }
torch = { version = "2.0.0", optional = true }
torchaudio = { version = "2.0.1", optional = true }
trainer = { version = "0.0.20", optional = true }
trove-classifiers = { version = "2023.4.22", optional = true }
tts = { version = "0.13.3", optional = true }
tzdata = { version = "2023.3", optional = true }
tzlocal = { version = "4.3", optional = true }
umap-learn = { version = "0.5.1", optional = true }
unidic-lite = { version = "1.0.8", optional = true }
virtualenv = { version = "20.21.1", optional = true }
webencodings = { version = "0.5.1", optional = true }
werkzeug = { version = "2.2.3", optional = true }
xattr = { version = "0.10.1", optional = true }
zipp = { version = "3.15.0", optional = true }

[tool.poetry.extras]
io = ["pyaudio", "sounddevice"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
