---
name: Feature Request
description: Use this template for proposing new features.
title: "[Feature]: "
labels: ["feature", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: brief-description
    attributes:
      label: Brief Description
      description: Please summarize the proposed feature, specifying what it should do and why it would be useful.
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Please explain why this feature would be useful and how it would improve the project.
    validations:
      required: true
  - type: textarea
    id: suggested-implementation
    attributes:
      label: Suggested Implementation
      description: If possible, provide details about how this feature could be implemented.
    validations:
      required: false
---




